### ISSUE TITLE
Create checking of SMTP server response for errors

### ISSUE THREAD

**Issue by bryan-robitaille** [gctools-outilsgc/notification-service#5]
## Context
The `sendEmail()` function currently only checks if the task errors out.  Only errors that are related to network connectivity would currently be caught.  A secondary check on the response from `mailer.sendMail()` should be done to verify if the upstream server has sent back any errors.  

## Expected Behavior
An email is sent to a SMTP server.  The server cannot send at this time.  The notification service sets the status of the email to Queued for sending at a later time.

**Comment by Steph4104** [comment]
When using nodemailer, I can send an email to an invalid email and I still receive a OK response from nodemailer: 
![image](https://user-images.githubusercontent.com/15112568/54760404-6c0e6000-4bc6-11e9-9b7c-2303929c06e5.png)

From the email I use from the SMTP, I receive a "no found email"

I make some research and I found this issue on nodemailer github: https://github.com/nodemailer/nodemailer/issues/414

Base on this answer, Nodemailer **can't know** if the email is properly send or not.

Here is a similar answer on this subject: https://stackoverflow.com/questions/37940642/how-to-enable-error-in-nodemailer-if-email-is-not-exist

**Comment by bryan-robitaille** [comment]
Thanks for the research @Steph4104 !
